name: Gradle_Build_for_jvm-tasks_with_JFrog_Artifactory

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  actions: read           # for detecting the Github Actions environment
  id-token: write         # for creating OIDC tokens for signing
  packages: write         # for uploading attestations
  contents: read          # read the contents permission
  security-events: write  # for uploading code scanning

jobs:
  build:
    name: 'Gradle_build_for_jvm-tasks'
    env:
      JFROG_CLI_BUILD_NAME: 'jvm-tasks-gradle'
      JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      JFROG_CLI_BUILD_PROJECT: ${{ vars.JF_PROJECT }}
      JFROG_CLI_LOG_LEVEL: INFO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
      
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: rodolphef-jvmtasks
          oidc-audience: rodolphef-jvmtasks
          
      - name: Configure Build
        run: |
          jf gradle-config --use-wrapper="true" --repo-resolve soleng.dev.gradle.virtual --repo-deploy soleng.dev.gradle.virtual
      
      - name: JFrog Curation Audit
        run: |
          jf mvn-config --repo-resolve-releases mikeho-jvm-tasks-gradle-remote --repo-resolve-snapshots soleng.dev.gradle.virtual --repo-deploy-releases soleng.dev.gradle.virtual --repo-deploy-snapshots soleng.dev.gradle.virtual
          echo "jvmtasksArtifactName=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "jvmtasksVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          jf curation-audit
      
      - name: Audit Source Code
        run: |
          jf audit --licenses --format=table --gradle=true
          
      - name: Build Gradle package
        run: |
          jf gradle clean build --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} --project=${{ env.JFROG_CLI_BUILD_PROJECT }}
          jf gradle artifactoryPublish --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} --project=${{ env.JFROG_CLI_BUILD_PROJECT }}     
      
      - name: Publish build info
        if: github.ref == 'refs/heads/master'
        run: |
          # Collect environment variables for the build
          jf rt build-collect-env --project ${{ env.JFROG_CLI_BUILD_PROJECT }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}  
          # Collect VCS details from Git and add them to the build
          jf rt build-add-git --project ${{ env.JFROG_CLI_BUILD_PROJECT }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}
          jf rt build-publish --project ${{ env.JFROG_CLI_BUILD_PROJECT }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}
      
      - name: Scan build
        if: github.ref == 'refs/heads/master'
        run: |
          jf build-scan --vuln --fail=false --project=${{ env.JFROG_CLI_BUILD_PROJECT }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}  
     
